# Generated by Django 4.2.15 on 2025-03-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
